WIP: Feature/oauth
meateam/api-gateway pull request #143
Opened 2020-05-26 10:09 UTC by AllKinds

2020-06-01 07:26 UTC, Shahar-Y commented
Also, please approve that it was tested in the kubernetes

2020-06-02 09:15 UTC, Shahar-Y commented on oauth/oauth.go
> +	// temporary
?

2020-06-02 09:15 UTC, Shahar-Y commented on oauth/oauth.go
> +	// temporary
?

2020-06-07 12:37 UTC, Shahar-Y commented on oauth/oauth.go
> +	// temporary
```suggestion
	//  temporary
```

2020-11-01 07:50 UTC, Shahar-Y requested changes

2020-11-01 07:50 UTC, Shahar-Y commented on oauth/oauth.go
> +	// ServiceAuthTypeValue is the value of service for AuthTypeHeader key
Bad comment

2020-11-01 07:50 UTC, Shahar-Y commented on oauth/oauth.go
>  	ServiceAuthTypeValue = "Service"
Add a comment which says that this will be deprecated

2020-11-01 07:50 UTC, Shahar-Y commented on oauth/oauth.go
>  	ServiceAuthTypeValue = "Service"
Also, remove `OutAdminScope`. It's irrelevant.

2020-11-01 07:50 UTC, Shahar-Y commented on oauth/oauth.go
> +		case ServiceAuthTypeValue:
Add comment that this header value is deprecated

2020-11-01 11:43 UTC, AllKinds commented on oauth/oauth.go
> +	// ServiceAuthTypeValue is the value of service for AuthTypeHeader key
```suggestion
	// DropboxAuthTypeValue is the value of the AuthTypeHeader key for the Dropbox services
```

2020-11-01 11:47 UTC, AllKinds commented on oauth/oauth.go
> +		case ServiceAuthTypeValue:
```suggestion
              // DEPRECATED: this case should be delete in the next version 
		case ServiceAuthTypeValue:
```

2020-11-01 12:14 UTC, AllKinds commented on oauth/oauth.go
> +	// temporary
This code's purpose is to allow Dropbox to preform any action it wants (in the name of an external user) without validating that it (Dropbox) has the corresponding scopes.
This should be deleted after successfully integrating with Dropbox (with an emphasis on the correct scopes).

2020-11-01 12:14 UTC, AllKinds commented on oauth/oauth.go
> +	// temporary
replied in the next comment

2020-11-01 12:19 UTC, AllKinds commented on oauth/oauth.go
> +              // DEPRECATED: this case should be delete in the next version
```suggestion
              // DEPRECATED: this case should be deleted in the next version 
```

2020-11-01 12:20 UTC, AllKinds commented on server/auth/auth.go
>  	// ServiceAuthTypeValue is the value of service for AuthTypeHeader key
```suggestion
	// DEPRECATED: ServiceAuthTypeValue is the value of service for AuthTypeHeader key
```

2020-11-01 12:21 UTC, AllKinds commented on oauth/oauth.go
>  	// ServiceAuthTypeValue is the value of service for AuthTypeHeader key
```suggestion
	// DEPRECATED: ServiceAuthTypeValue is the value of service for AuthTypeHeader key
```

2020-11-01 12:25 UTC, AllKinds commented on oauth/oauth.go
> +		case ServiceAuthTypeValue:
added

2020-11-01 12:25 UTC, AllKinds commented on oauth/oauth.go
>  	ServiceAuthTypeValue = "Service"
done

2020-11-01 12:25 UTC, AllKinds commented on oauth/oauth.go
> +	// ServiceAuthTypeValue is the value of service for AuthTypeHeader key
edited

2020-11-01 13:05 UTC, merged