update mime type and extension
meateam/api-gateway pull request #167
Opened 2020-08-17 10:36 UTC by yosef32

2020-09-24 07:20 UTC, Shahar-Y requested changes
Run it in the k8s and add a link

2020-09-24 07:20 UTC, Shahar-Y commented on upload/update.go
> +// changeExtensionByMimeType return the same file name and change the extention by the mime type
```suggestion
// changeExtensionByMimeType returns the same file name and changes the extension by the mime type
```

2020-09-24 07:20 UTC, Shahar-Y commented on upload/update.go
> +// It is only for docs
```suggestion
// This function is only used for the docs
```

2020-10-11 11:30 UTC, Shahar-Y requested changes

2020-10-11 11:30 UTC, Shahar-Y commented on upload/update.go
> +}
This overrides the last part of the array. 
Check if there is an extension name, if yes -> override it, if not-> add the extension

2020-11-15 18:56 UTC, yosef32 commented on upload/update.go
> +}
done

2020-11-15 20:03 UTC, Shahar-Y requested changes
Moving to changes required until testing with Docs are approved

2020-11-15 20:03 UTC, Shahar-Y commented on upload/update.go
> +		mimeType = resp.GetContentType()
How can there be two mime type sources? (c.GetHeader(MimeTypeHeader), resp.GetContentType())

2020-11-15 20:04 UTC, Shahar-Y commented on upload/update.go
> +}
Then it needs to be tested before review

2020-11-23 12:36 UTC, yosef32 commented on upload/update.go
> +		mimeType = resp.GetContentType()
When you update a regular file it returns mime type from S3, and when you change only the mime type then it is sent in the headers

2020-11-23 12:37 UTC, merged