Documentation/swagger
meateam/api-gateway pull request #185
Opened 2020-11-03 10:56 UTC by yosef32

2020-11-04 12:55 UTC, Shahar-Y requested changes
- [ ] Deploy in your environment.
 - [ ] Add documentation in the PR on how to use the swagger.
 - [ ] Add changes to CHANGELOG.md

2020-11-04 12:55 UTC, Shahar-Y commented on docker-compose.yml
> -    environment:
Why was it changed?

2020-11-04 12:55 UTC, Shahar-Y commented on Dockerfile
> -COPY --from=builder /go/src/app/api-gateway /api-gateway
why? and by how much has the size of the image increased?

2020-11-08 07:37 UTC, yosef32 commented on Dockerfile
> -COPY --from=builder /go/src/app/api-gateway /api-gateway
done

2020-11-08 14:50 UTC, Shahar-Y requested changes
Upload to your environment, and add to the changelog

2020-11-08 14:50 UTC, Shahar-Y commented on server/router.go
> +	if viper.GetString(configDeployment) == "prodaction" {
1. Was it tested with and without the environment variable? 
2. Change `prodaction` to `production`.
3. the string `production` should be a constant.

2020-11-08 14:50 UTC, Shahar-Y commented on server/server.go
> +	viper.SetDefault(configDeployment, "integration")
Is it good that the default is integration which allows more options for the user? 
On second thought, maybe it is better to have an environment variable which says "allow swagger?" and the default would be false.

2020-11-08 14:50 UTC, Shahar-Y commented on swagger/file.swagger.go
> +// This will return all files according to the requested folder
remove `will`, ass `s` to returns on all occurrences

2020-11-09 08:01 UTC, yosef32 commented on docker-compose.yml
> -    environment:
done

2020-11-09 08:05 UTC, yosef32 commented on server/router.go
> +	if viper.GetString(configDeployment) == "prodaction" {
1. yes
2. done
3. done

2020-11-09 08:07 UTC, yosef32 commented on server/server.go
> +	viper.SetDefault(configDeployment, "integration")
Yes because the development environment is integration

2020-11-09 08:12 UTC, yosef32 commented on swagger/file.swagger.go
> +// This will return all files according to the requested folder
done

2020-11-09 15:30 UTC, Shahar-Y requested changes

2020-11-09 15:30 UTC, Shahar-Y commented on CHANGELOG.md
> +  - Naw can go to /api/docs and see the documentation
```suggestion
  - Now you can go to /api/docs and see the documentation 
```

2020-11-09 15:30 UTC, Shahar-Y commented on server/server.go
> +	viper.SetDefault(configDeployment, "integration")
But you want the default to be safer, without an option to make changes in prod

2020-11-09 15:30 UTC, Shahar-Y commented on swagger/permit.swagger.go
> +// This will update the permits to the file
```suggestion
// This updates the permits to the file
```

2020-11-12 09:15 UTC, yosef32 commented on server/server.go
> +	viper.SetDefault(configDeployment, "integration")
done

2020-11-12 13:24 UTC, Shahar-Y requested changes

2020-11-12 13:24 UTC, Shahar-Y commented on server/router.go
> +			RedocURL:  "/api/redoc",
Wait, so production allows redoc?
I believe that the best solution is to use the basic swagger by default, and if the environment is "integration" - then add redoc

2020-11-15 05:33 UTC, yosef32 commented on server/router.go
> +			RedocURL:  "/api/redoc",
done

2020-11-15 21:00 UTC, Shahar-Y approved these changes

2020-11-15 21:01 UTC, Shahar-Y commented
@yosef32 make sure you resolve the conflicts in the changelog properly

2020-11-22 10:43 UTC, Shahar-Y submitted a review, later dismissed

2020-11-23 13:18 UTC, Shahar-Y approved these changes

2020-11-23 13:18 UTC, merged