Fix/fetch shared files
meateam/api-gateway pull request #204
Opened 2020-12-10 14:32 UTC by nettashviro

fix the fetching of getSharedFIles. related to pr

2020-12-13 10:36 UTC, Shahar-Y requested changes
Please add more documentation about the change: 
what changed in the return value, and what was it before the change? And the meaning of the new fields.

2020-12-13 11:22 UTC, nettashviro commented on CHANGELOG.md
> +- Fix the fetching of GetSharedFiles bug that returns 404.
done

2020-12-27 10:52 UTC, Shahar-Y requested changes
Other than the comment, looks great! 
After it's approved, don't merge yet

2020-12-27 10:52 UTC, Shahar-Y commented on server/auth/auth.go
> +	c.Set(oauth.ContextAppKey, oauth.DriveAppID)
Why twice?

2020-12-27 12:58 UTC, Shahar-Y submitted a review, later dismissed
Looks good, Don't merge

2021-05-24 07:31 UTC, closed without merging