Fix/change delete file
meateam/api-gateway pull request #209
Opened 2020-12-30 09:22 UTC by nettashviro

I changed the delete order between the file and its permissions, I also added a rollback mechanism that adds the permissions back in case something fails with the deleting of the file.

2020-12-30 13:50 UTC, Shahar-Y requested changes

2020-12-30 13:50 UTC, Shahar-Y commented on CHANGELOG.md
> +
This should be under `Unreleased`

2020-12-30 13:50 UTC, Shahar-Y commented on file/controller.go
> +		AddPermissionsOnError(ctx, err, fileID, filePermissions.GetPermissions(), permissionClient, logger)
What if the error is 404? Should we still restore the permissions? - The file does not exist

2020-12-30 13:50 UTC, Shahar-Y commented on file/controller.go
> +func deleteFileAndPrem(ctx *gin.Context,
Looks good, what about the permits of the file?

2020-12-30 13:50 UTC, Shahar-Y commented on upload/upload.go
> +	_, deleteErr := file.DeleteFile(c,
What is that?

2020-12-30 13:51 UTC, Shahar-Y commented
Also, notice the branch is out-of-date

2020-12-30 14:14 UTC, nettashviro commented on CHANGELOG.md
> +
done

2020-12-30 14:14 UTC, nettashviro commented on file/controller.go
> +		AddPermissionsOnError(ctx, err, fileID, filePermissions.GetPermissions(), permissionClient, logger)
done

2020-12-30 14:16 UTC, nettashviro commented on file/controller.go
> +func deleteFileAndPrem(ctx *gin.Context,
In the original deletion, there is no reference to deleting a permit. I meant "perm" as a shortcut for "permissions".  I'll change the name of the function

2020-12-30 14:30 UTC, nettashviro commented on upload/upload.go
> +	_, deleteErr := file.DeleteFile(c,
I changed DeleteFile function parameters from context.Context to gin.Context.
gin.Context already is a context.Context and implements all its functions. 
I had to use functionality that does not exist in context.Context (such as c.AbortWithStatus)

2021-01-03 07:05 UTC, Shahar-Y approved these changes
Don't push to develop

2021-05-23 09:40 UTC, Shahar-Y approved these changes

2021-05-23 09:40 UTC, merged