hotfix: Improved metrics
meateam/api-gateway pull request #217
Opened 2021-03-01 11:07 UTC by Shahar-Y

Added appID and AuthType to the metrics, with an option to add mre info from claims.
No breaking changes, and tested with kibana locally
Signed-off-by: shahar-y <shya95@gmail.com>

2021-03-10 08:48 UTC, yoavrozner requested changes
Dear @Shahar-Y, please remove the dropbox changes because it is impossible to review both changes that are unrelated to each other. Furthermore, If I would approve it, the dropbox changes might not get reviewed and still be in the develop. Quick solution: open a new branch from dropbox branch, and open PR from `hotfix: Improved metrics` to the new branch and the changes should not appear.

2021-03-10 08:48 UTC, yoavrozner commented on docker-compose.yml
> +version: '2.1'
Why?

2021-03-11 08:33 UTC, Shahar-Y commented
> Dear @Shahar-Y, please remove the dropbox changes because it is impossible to review both changes that are unrelated to each other. Furthermore, If I would approve it, the dropbox changes might not get reviewed and still be in the develop. Quick solution: open a new branch from dropbox branch, and open PR from `hotfix: Improved metrics` to the new branch and the changes should not appear.

But that's what I did, here: https://github.com/meateam/api-gateway/pull/220

2021-03-15 11:13 UTC, Shahar-Y commented
Closing in favor of #223

2021-03-15 11:13 UTC, closed without merging