Feature/search by mail or t
meateam/api-gateway pull request #218
Opened 2021-03-01 14:23 UTC by yoavrozner

2021-03-02 11:43 UTC, Shahar-Y requested changes
It works, but needs some fixing. Still, good job for a first push attempt in golang :+1: 
Also, notice that by requesting from the same route - you get two different types of results (one as an object and the other as an array of objects). Think about a solution for that

2021-03-02 11:43 UTC, Shahar-Y commented on CHANGELOG.md
> +
Add it under ## Unreleased, and not as a version. The version is for pushong to prod, which we will do in this case only after fixes and testing in integration.
In addition, write according to the forma:
```hotfix\minor\major: ([xx](https://github.com/meateam/drive-ui/pull/xx)): add advance search by mail/T```

2021-03-02 11:43 UTC, Shahar-Y commented on user/user.go
> +)
Consts must be initiated with a fixed value. Also, enum is a better word than flag for enums (same as in the other cr). 
Check on how to use enums in golang.

2021-03-02 11:43 UTC, Shahar-Y commented on user/user.go
> +	userT := c.Query(ParamPartialName)
is it still partial name?

2021-03-02 11:43 UTC, Shahar-Y commented on user/user.go
> +	mail := c.Query(ParamPartialName)
is it still partial name?
change it perhaps to the combination of `ParamRequestContent` instead of ParamPartialName and `ParamSearchType` as enum instead of ParamSearchByFlag

2021-03-02 11:43 UTC, Shahar-Y commented on user/user.go
> +}
Make the function public (by renaming it to `StringToInt64` in `file.go`), and then import it instead of code duplication.

2021-03-02 11:43 UTC, Shahar-Y commented on user/user.go
> +	}
so.. by mail or by T?

2021-03-02 11:53 UTC, yoavrozner commented on user/user.go
> +	}
Both are in that single route due to the fact that kartoffel finds by userT and Mail in the same route so I thought it won't be necessary to create in the user-service a new route just for that minor change. Furthermore, I have added documentation above it to explain.

2021-03-02 12:11 UTC, yoavrozner commented on user/user.go
> +)
Please checkout the following articles about Enums in Golang:
[](https://stackoverflow.com/questions/14426366/what-is-an-idiomatic-way-of-representing-enums-in-go)
[](https://yourbasic.org/golang/iota/)

2021-03-02 12:15 UTC, yoavrozner commented on user/user.go
> +	mail := c.Query(ParamPartialName)
I can replace the variable name of ParamPartialName to ParamRequestContent easily but its value will be breaking changes. Please put it in your consideration.

2021-03-02 12:17 UTC, yoavrozner commented on user/user.go
> +	userT := c.Query(ParamPartialName)
It is not.
Because it is not a partial name, please answer https://github.com/meateam/api-gateway/pull/218#discussion_r585487531.

2021-03-02 15:44 UTC, Shahar-Y commented on user/user.go
> +)
Every day you learn something new. 
One mre thing - why not use it as a new type instead of unrelated consts? Example in: https://www.educative.io/edpresso/what-is-an-enum-in-golang

2021-03-02 15:47 UTC, Shahar-Y commented on user/user.go
> +	mail := c.Query(ParamPartialName)
It will be bad practice to keep using it as partialName with mail\T. So the two options I can see are to either cause breaking changes - or create a new route. What do you think is best?

2021-03-02 15:50 UTC, Shahar-Y commented on user/user.go
> +	}
Ok, so maybe rename the param name to `MailOrT` instead of just `Mail`. It will be very confusiing to use it the same way in the future

2021-03-02 15:52 UTC, Shahar-Y commented
Also, please add a description in the PR above so it will be easier for others (or for you in the future) to understand the changes made in the branch

2021-03-04 11:56 UTC, yoavrozner commented on user/user.go
> +	mail := c.Query(ParamPartialName)
In case the changes will only be in the gateway and the ui, I think it would be best to change from partial to some other alias.
However, if the changes may effect more services, I think it is the best to leave it so we won't break things.

2021-03-04 11:59 UTC, yoavrozner commented on user/user.go
> +	}
Seems right but firstly I need help in [https://github.com/meateam/user-service/issues/82#issuecomment-763468765](url)

2021-03-04 12:01 UTC, yoavrozner commented on user/user.go
> +)
Agreed

2021-03-04 13:42 UTC, Shahar-Y commented on user/user.go
> +	mail := c.Query(ParamPartialName)
The only breaking changes will be in the UI and won't be hard to fix (no other service calls the GW). 
So I believe it is best to choose one of the two options above

2021-03-15 08:04 UTC, Shahar-Y requested changes
Good progress. Talk to me about the enum in the route so we can find a solution to the query param

2021-03-15 08:04 UTC, Shahar-Y commented on user/user.go
> +	searchBy := searchByEnum(utils.StringToInt64(c.Query(ParamSearchType)))
I just realized that the `ParamSearchType` would be a number sent from the client. That means that any client would have to know the mapping of the numbers to the search types it wants, which could be problematic and non-RESTy as far as I know. 
The query string has to be a meaningful string and not a meaningless random number. 
A possible solution would be to map the meaningful strings to the enum you wrote via a function (switch-case)

2021-03-15 08:04 UTC, Shahar-Y commented on user/user.go
> +	}
Resolved?

2021-03-15 08:04 UTC, Shahar-Y commented on user/user.go
> +func userResponseToUsersResponse(user *uspb.GetUserResponse) usersResponse {
Please add a description, the name is very confusing. Maybe also change to `encapulateUserResponse`

2021-03-15 08:04 UTC, Shahar-Y commented on utils/utils.go
> +func StringToInt64(s string) int64 {
nice

2021-03-15 08:04 UTC, Shahar-Y commented on user/user.go
> +type usersResponse struct {
add a description for the type and where is it used

2021-03-22 07:55 UTC, yoavrozner commented on CHANGELOG.md
> +- FEAT([218](https://github.com/meateam/api-gateway/pull/218)): add advance search by mail/T.
major

2021-03-22 08:15 UTC, yoavrozner commented on user/user.go
> +	searchBy := searchByEnum(utils.StringToInt64(c.Query(ParamSearchType)))
Ok

2021-03-22 12:01 UTC, yoavrozner commented on user/user.go
> +	}
Yes

2021-03-23 09:04 UTC, nettashviro approved these changes

2021-04-11 07:11 UTC, nettashviro requested changes

2021-04-11 07:11 UTC, nettashviro commented on CHANGELOG.md
> +- major: ([218](https://github.com/meateam/api-gateway/pull/218)): add advance search by mail/T.
```suggestion
- minor: ([218](https://github.com/meateam/api-gateway/pull/218)): add advance search by mail/T.
```
and please add new version

2021-04-11 07:16 UTC, yoavrozner commented on CHANGELOG.md
> +- major: ([218](https://github.com/meateam/api-gateway/pull/218)): add advance search by mail/T.
Done.

2021-04-11 07:18 UTC, nettashviro submitted a review, later dismissed

2021-04-11 08:00 UTC, nettashviro approved these changes

2021-04-11 08:00 UTC, nettashviro requested changes
fix conflictts

2021-04-12 09:10 UTC, yoavrozner commented
Done @nettashviro

2021-04-19 13:43 UTC, Shahar-Y approved these changes

2021-04-20 08:25 UTC, nettashviro approved these changes

2021-04-20 10:06 UTC, merged