Feature/add cts intergation
meateam/api-gateway pull request #219
Opened 2021-03-07 13:41 UTC by nettashviro

2021-03-23 09:32 UTC, Shahar-Y requested changes

2021-03-23 09:32 UTC, Shahar-Y commented on dropbox/dropbox.go
> +func (r *Router) GetUserFilePermission(c *gin.Context, fileID string, role ppb.Role) bool {
Why not use `permission.IsPermitted` ?

2021-03-23 09:32 UTC, Shahar-Y commented on dropbox/dropbox.go
> +// must required a destination header
```suggestion
// Requires a destination header
```

2021-03-23 09:32 UTC, Shahar-Y commented on swagger/swagger.json
> +      "x-go-package": "github.com/meateam/permit-service/proto"
remove permit-service

2021-03-23 09:32 UTC, Shahar-Y commented on swagger/swagger.json
> +      "x-go-package": "github.com/meateam/permit-service/proto"
remove permit-service

2021-03-23 09:32 UTC, Shahar-Y commented on docker-compose.yml
>    permit-service:
remove permit-service and add dropbox-service

2021-03-23 09:32 UTC, Shahar-Y commented on swagger/swagger.json
> +{
Remove delegation from `swagger/ui/swagger.json`

2021-03-23 09:38 UTC, Shahar-Y commented
And change `transferd` to `transferred`

2021-03-23 10:06 UTC, nettashviro commented on dropbox/dropbox.go
> +// must required a destination header
done

2021-03-23 10:06 UTC, nettashviro commented on swagger/swagger.json
> +      "x-go-package": "github.com/meateam/permit-service/proto"
done

2021-03-23 10:07 UTC, nettashviro commented on docker-compose.yml
>    permit-service:
done

2021-03-23 10:14 UTC, nettashviro commented on swagger/swagger.json
> +{
done

2021-03-23 10:47 UTC, nettashviro commented on dropbox/dropbox.go
> +func (r *Router) GetUserFilePermission(c *gin.Context, fileID string, role ppb.Role) bool {
because we need to check if the user is the owner/

> And change `transferd` to `transferred`

where?

2021-03-23 10:47 UTC, nettashviro commented on dropbox/dropbox.go
> +func (r *Router) GetUserFilePermission(c *gin.Context, fileID string, role ppb.Role) bool {
because we need to check if the user is the owner/

> And change `transferd` to `transferred`

where?

2021-03-23 10:47 UTC, nettashviro commented on swagger/swagger.json
> +      "x-go-package": "github.com/meateam/permit-service/proto"
done

2021-03-23 10:47 UTC, nettashviro commented
> And change `transferd` to `transferred`

there is no instance of 'transferd'

2021-03-23 11:31 UTC, nettashviro commented on dropbox/dropbox.go
> +func (r *Router) GetUserFilePermission(c *gin.Context, fileID string, role ppb.Role) bool {
done

2021-03-23 15:16 UTC, Shahar-Y approved these changes
Great work!

2021-03-25 13:52 UTC, yoavrozner approved these changes

2021-03-25 14:20 UTC, merged