Hotfix/metrics - for CR puposes
meateam/api-gateway pull request #220
Opened 2021-03-10 08:00 UTC by Shahar-Y

Added appID and AuthType to the metrics, with an option to add mre info from claims.
No breaking changes, and tested with kibana locally.

Will not merge. the relevant PR is here: https://github.com/meateam/api-gateway/pull/217
Signed-off-by: shahar-y shya95@gmail.com

2021-03-10 09:06 UTC, yoavrozner commented
Please see [https://github.com/meateam/api-gateway/pull/217#pullrequestreview-608448980](url)

2021-03-14 12:16 UTC, yoavrozner commented on server/metrics.go
> +		authType = "NoneAuthType"
I think you should do:
`authType = NoAuthType`
so you will be able to alter only the constant NoAuthType value without the need to alter the "NoneAuthType" string here.

2021-03-14 12:16 UTC, yoavrozner commented on oauth/oauth.go
> +func ExtractTokenFromHeader(ctx *gin.Context) (string, error) {
Why is this meant to be exported? I don't see another use of it.

2021-03-14 12:16 UTC, yoavrozner commented on server/metrics.go
> +		spikeToken, err := oauth.ExtractTokenFromHeader(c)
Don't you have ExtractTokenFromHeader func already? Maybe it relates to:

2021-03-14 13:55 UTC, Shahar-Y commented on oauth/oauth.go
> +func ExtractTokenFromHeader(ctx *gin.Context) (string, error) {
It is used in `metrics.go`. I exported it to avoid code duplication

2021-03-14 13:55 UTC, Shahar-Y commented on server/metrics.go
> +		spikeToken, err := oauth.ExtractTokenFromHeader(c)
Yup, that's exactly it. I used it to avoid code duplication

2021-03-15 11:04 UTC, Shahar-Y commented on server/metrics.go
> +		authType = "NoneAuthType"
Correct, I missed it

2021-03-15 11:12 UTC, Shahar-Y commented on docker-compose.yml
> +version: '2.1'
The version does not work and need fixing

2021-03-21 09:44 UTC, yoavrozner commented on docker-compose.yml
> +version: '2.1'
Please set a date and we will solve this issue once and for all.

2021-05-03 07:31 UTC, yoavrozner requested changes
@Shahar-Y for next time please read and implement the review comments before you ask me to review your PR again.

2021-05-03 07:31 UTC, yoavrozner commented on server/metrics.go
> +		appID, _ = claims["clientName"].(string) // get the appID from the claims
"clientName" should be a constant with name that explains the use of it.

2021-05-03 07:31 UTC, yoavrozner commented on server/metrics.go
> +		authType = "NoneAuthType"
And didn't change it...

2021-05-03 09:37 UTC, Shahar-Y commented
Closing. The PR is in #223

2021-05-03 09:37 UTC, closed without merging