copy file
meateam/api-gateway pull request #259
Opened 2021-12-21 13:34 UTC by maya-fisher

2021-12-21 14:20 UTC, sternomer approved these changes

2021-12-21 15:51 UTC, yoavrozner requested changes
Well done!

2021-12-21 15:51 UTC, yoavrozner commented on file/file.go
> +	CopyFileRole = ppb.Role_READ
Please check

2021-12-21 15:51 UTC, yoavrozner commented on file/file.go
> +		newFileName = ""
Reeturn error!

2021-12-21 15:51 UTC, yoavrozner commented on file/file.go
> +	}
Triple check

2021-12-21 15:51 UTC, yoavrozner commented on file/file.go
> +	}
Check it out Rollback

2021-12-21 15:51 UTC, yoavrozner commented on file/file.go
> +	}
What?

2021-12-21 15:51 UTC, yoavrozner commented on file/file.go
> +	}
Rollback

2021-12-21 15:51 UTC, yoavrozner commented on file/file.go
> +}
Utils please

2021-12-21 15:56 UTC, maya-fisher commented on file/file.go
> +	CopyFileRole = ppb.Role_READ
It's the same as in favorite

2021-12-21 16:00 UTC, maya-fisher commented on file/file.go
> +		newFileName = ""
Done

2021-12-21 16:01 UTC, maya-fisher commented on file/file.go
> +	}
Done

2021-12-21 18:11 UTC, maya-fisher commented on file/file.go
> +	}
Done. but need to check

2021-12-21 18:12 UTC, maya-fisher commented on file/file.go
> +	}
Done, but need to check

2021-12-26 09:48 UTC, yoavrozner submitted a review, later dismissed
Good job @maya-fisher

2021-12-26 09:51 UTC, yoavrozner commented on file/file.go
> +	if newFileName == "undefined" {
```suggestion
	if newFileName == "undefined" || newFileName == "" {
```

2022-01-11 09:19 UTC, yarinBenisty approved these changes

2022-01-17 12:19 UTC, merged